### ISSUE TITLE
changing tooltip css

### ISSUE THREAD

**Issue by seanmccay** [creativetimofficial/ct-light-bootstrap-dashboard-pro-react#4]
I'm trying to make my tooltips black with white text. I was able to do that for the text bubble, but the arrow is still yellow and my selectors don't seem to catch it.

Here's my selector:
```css
.tooltip-inner,.tooltip-arrow {
    background-color: black;
    color: white;
}
```
I also tried the solution shown here in this [StackOverflow Question](https://stackoverflow.com/questions/17642447/change-bootstrap-tooltip-color)

```css
.tooltip-arrow,
.red-tooltip + .tooltip > .tooltip-inner {background-color: #f00;}

.red-tooltip + .tooltip.top > .tooltip-arrow {background-color: #f00;}
```

Have yall messed with this before?
